jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: action/checkout@v3
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: echo "test multiple container"
    - run: docker build -t [docker_hub_id]/react-test-app -f ./frontend/Dockerfile.dev ./frontend
    - run: docker run -e CI=true chrismrkr/react-test-app npm test

    - run: docker build -t [docker_hub_id]/docker-frontend ./frontend
    - run: docker build -t [docker_hub_id]/docker-nginx ./nginx
    - run: docker build -t [docker_hub_id]/docker-backend ./backend

    - run: docker push [docker_hub_id]/docker-frontend
    - run: docker push [docker_hub_id]/docker-nginx
    - run: docker push [docker_hub_id]/docker-backend

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git'
    
    - name: Deploy to EB
      uses: einargilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: fullstack-docker-app
        environment_name: Fullstack-docker-app-env
        existing_bucket_name:
        region:
        version_label:
        deployment_package: deploy.zip
