version: "3"
services:
  frontend:
    image: [이미지 이름(docker_hub_id/docker-frontend)]
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx: 
    restart: always
    image: [이미지 이름(docker_hub_id/docker_nginx)]
    ports: 
      - "80:80"

  backend:
    image: [이미지 이름(docker_hub_id/docker-backend)]
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT   
